# Generated by Django 5.0.6 on 2025-06-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reg_user',
            name='confirm_password',
        ),
        migrations.AlterField(
            model_name='reg_user',
            name='password',
            field=models.CharField(max_length=150),
        ),
    ]
