# Generated by Django 5.0.6 on 2025-07-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_cars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='category',
            field=models.CharField(choices=[('hatchback', 'Hatchback'), ('sedan', 'Sedan'), ('suv', 'SUV'), ('van', 'Van / Minivan'), ('luxury', 'Luxury'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], max_length=20, verbose_name='Category'),
        ),
    ]
