# Generated by Django 5.0.6 on 2025-07-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_alter_cars_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='location',
            field=models.CharField(default='Pune', max_length=100),
        ),
    ]
