# Generated by Django 5.0.6 on 2025-07-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='name',
            field=models.CharField(max_length=100, verbose_name='{i.name}'),
        ),
    ]
