# Generated by Django 5.0.6 on 2025-08-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_alter_cars_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
