# Generated by Django 5.0.6 on 2025-08-11 15:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0010_cars_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='address',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='booking',
            name='license_no',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='mobile',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='drop_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
