# Generated by Django 5.0.6 on 2025-09-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0011_booking_address_booking_license_no_booking_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='No_of_Days',
            field=models.CharField(default='N/A', max_length=11),
        ),
    ]
