# Generated by Django 5.0.6 on 2025-09-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0012_booking_no_of_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='addhar_image',
            field=models.ImageField(blank=True, null=True, upload_to='addhar/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='license_image',
            field=models.ImageField(blank=True, null=True, upload_to='licenses/'),
        ),
    ]
