# Generated by Django 5.0.6 on 2025-09-08 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0013_booking_addhar_image_booking_license_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='No_of_Days',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='addhar_image',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='license_image',
        ),
        migrations.AddField(
            model_name='booking',
            name='addhar_file',
            field=models.FileField(blank=True, null=True, upload_to='addhar/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='license_file',
            field=models.FileField(blank=True, null=True, upload_to='licenses/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='no_of_days',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
