# Generated by Django 5.0.6 on 2025-09-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0014_remove_booking_no_of_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
