# Generated by Django 5.0.6 on 2025-09-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0015_alter_booking_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='drop_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup_datetime',
            field=models.DateTimeField(),
        ),
    ]
