# Generated by Django 5.0.6 on 2025-09-09 09:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0016_alter_booking_drop_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='drop_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
