# Generated by Django 5.0.6 on 2025-09-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0017_alter_booking_drop_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
