# Generated by Django 5.0.6 on 2025-09-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0018_booking_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
