# Generated by Django 5.0.6 on 2025-09-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0019_booking_pickup_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reg_user',
        ),
        migrations.AlterField(
            model_name='cars',
            name='category',
            field=models.CharField(choices=[('hatchback', 'Hatchback'), ('sedan', 'Sedan'), ('suv', 'SUV'), ('van', 'Van / Minivan'), ('luxury', 'Luxury'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cars',
            name='description',
            field=models.TextField(default='Car description'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
