# Generated by Django 5.0.6 on 2025-09-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0020_delete_reg_user_alter_cars_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
